owner: TicketOpen
repo: status

sites:
  - name: Melon Ticket
    url: https://ticket.melon.com
  - name: Interpark Ticket
    url: http://ticket.interpark.com
  - name: YES24 Ticket
    url: http://ticket.yes24.com
  - name: Ticketlink
    url: https://ticket.wemakeprice.com
  - name: WE MAKE CURTURE
    url: https://ticket.wemakeprice.com
  - name: NAVER LIVE
    url: https://live.naver.com
  - name: V LIVE
    url: https://www.vlive.tv
  - name: YouTube
    url: https://www.youtube.com
  - name: MyMusicTaste
    url: https://www.mymusictaste.com
  - name: danchu
    url: https://danchu.tv
  - name: bbangya tv
    url: https://www.bbangyatv.com            
    

assignees:
  - SOLPLPARTY
  - amblerkr

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for TicketOpen"
  introMessage: 티켓 예매사이트의 상태를 모니터링합니다.
  navbar:
